// <auto-generated />
using CamBotButHesFullOfDumbShite.PlayerLevelsDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CamBotButHesFullOfDumbShite.Migrations.PlayerLevelsEntitiesMigrations
{
    [DbContext(typeof(PlayerLevelsEntities))]
    partial class PlayerLevelsEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("CamBotButHesFullOfDumbShite.PlayerLevelsDatabase.PlayerLevelsModel", b =>
                {
                    b.Property<string>("playerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("playerUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("points")
                        .HasColumnType("TEXT");

                    b.HasKey("playerId");

                    b.ToTable("playerLevelsModel");
                });
#pragma warning restore 612, 618
        }
    }
}
